### ISSUE TITLE
Create release for Binja 3.0

### ISSUE THREAD

**Issue by clubby789** [whitequark/binja_itanium_cxx_abi#9]
The version of the plugin in the repo works in Binja 3, but it hasn't been updated in the plugin manager list. Would you mind creating a new Github release to update the manager version?

**Comment by whitequark** [comment]
Will do after #8 is completed.

**Comment by fabianfreyer** [comment]
Since #8 is closed, any chance to roll a new release?

**Comment by whitequark** [comment]
Done
